<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\petshopDomain\PetShopDomain.csproj" />
    <ProjectReference Include="..\petshopDal\PetShopDal.csproj" />
  </ItemGroup>

</Project>
